# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env.secret'
end

default_platform(:android)

platform :android do
  desc "Runs widget tests"
  lane :test do
    flutter(args: [
      "test",
      "../test"
    ])
  end

  desc "Build release appbundle"
  lane :appbundle do
    flutter(args: ["clean"])
    flutter(args: [
               "build",
               "appbundle",
               "--release",
               "-t", "lib/main.dart"
             ]
           )
  end

  desc "Build staging apk"
  lane :apk do
    flutter(args: ["clean"])
    flutter(args: [
               "build",
               "apk",
               "--release",
             ]
           )
  end

  desc "Deploy apk to Firebase App Distribution"
  lane :firebase do
    firebase_app_distribution(
      app: "#{ENV['FIREBASE_APP_ID']}",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "internal",
      release_notes_file: "../release_notes.txt",
      firebase_cli_token: "#{ENV['FIREBASE_CLI_TOKEN']}",
    )
  end

  desc "Deploy appbundle to Google Play Store. Internal track."
  lane :playstore_internal do
  upload_to_play_store(
    track: "internal",
    aab: "../build/app/outputs/bundle/release/app-release.aab",
    skip_upload_metadata: true,
    skip_upload_changelogs: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
  end
end
